import { ChatMessageItem } from '../types';

export function exportChatAsMarkdown(messages: ChatMessageItem[], studentName: string = 'Huskies Student') {
  if (!messages || messages.length === 0) return;

  const now = new Date();
  const dateStr = now.toLocaleDateString('en-CA', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const timeStr = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  let md = `# Saint Mary's University | Hi ._. Askey! Chat Session\n\n`;
  md += `> **Campus:** Saint Mary's University (923 Robie Street, Halifax, Nova Scotia, Canada)\n`;
  md += `> **Student:** ${studentName}\n`;
  md += `> **Session Exported:** ${dateStr} at ${timeStr}\n`;
  md += `> **Knowledge Base Index:** SMU-2024.3-Verified (Grounding Threshold: 0.82)\n\n`;
  md += `---\n\n`;

  messages.forEach((msg, idx) => {
    if (msg.role === 'user') {
      md += `## 👤 Question (${msg.timestamp})\n\n`;
      md += `${msg.content}\n\n`;
    } else {
      const confidence = msg.confidence ? ` (Confidence: ${Math.round(msg.confidence * 100)}% Grounded)` : '';
      md += `## 🎓 Hi ._. Askey! Answer${confidence} - ${msg.timestamp}\n\n`;
      md += `${msg.content}\n\n`;

      if (msg.sources && msg.sources.length > 0) {
        md += `### 📚 Verified Sources:\n`;
        msg.sources.forEach((src) => {
          md += `- [${src.title}](${src.url}) - *${src.type}*\n`;
          if (src.description) {
            md += `  > ${src.description}\n`;
          }
        });
        md += `\n`;
      }

      if (msg.suggestedFollowUps && msg.suggestedFollowUps.length > 0) {
        md += `### 💡 Suggested Follow-Up Questions:\n`;
        msg.suggestedFollowUps.forEach((q) => {
          md += `- ${q}\n`;
        });
        md += `\n`;
      }
    }
    md += `---\n\n`;
  });

  md += `\n*Export generated by Hi ._. Askey! - Official Saint Mary's University Knowledge Base RAG Assistant (smu.ca)*\n`;

  const filename = `smu-askey-chat-${now.toISOString().slice(0, 10)}.md`;
  downloadFile(md, filename, 'text/markdown;charset=utf-8');
}

export function exportChatAsJSON(messages: ChatMessageItem[], studentName: string = 'Huskies Student') {
  if (!messages || messages.length === 0) return;

  const now = new Date();
  const exportData = {
    institution: "Saint Mary's University",
    campus: "Halifax, Nova Scotia, Canada B3H 3C3",
    assistant: "Hi ._. Askey! Official AI",
    index: "SMU-2024.3-Verified",
    student: studentName,
    exportedAt: now.toISOString(),
    totalMessages: messages.length,
    messages: messages.map((m) => ({
      id: m.id,
      role: m.role,
      content: m.content,
      timestamp: m.timestamp,
      confidence: m.confidence,
      category: m.category,
      sources: m.sources,
      suggestedFollowUps: m.suggestedFollowUps,
      model: m.model,
    })),
  };

  const jsonString = JSON.stringify(exportData, null, 2);
  const filename = `smu-askey-chat-${now.toISOString().slice(0, 10)}.json`;
  downloadFile(jsonString, filename, 'application/json;charset=utf-8');
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
